configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkBadgeTesting/
        - Sources/SparkBadgeSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkBadgeTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkBadge]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkBadgeTesting/
        - Sources/SparkBadgeSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkBadgeTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkBadge]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkBadgeTesting/
        - Sources/SparkBadgeSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkBadgeTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkBadge]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkBadgeTesting/
        - Sources/SparkBadgeSnapshotTesting/
    templates:
      - .sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkBadgeTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkBadge]
